### ISSUE TITLE
Include kerberos authentication for facebook users

### ISSUE THREAD

**Issue by ConcurrencyPractitioner** [wilsonh1/ClubSignIn#3]
We want to make sure that facebook users are who they really are, so we should probably include some authentication process in our facebook server end which provide reasonable user security. Link below is strong candidate for kerberos implementation:

https://strongloop.com/strongblog/authenticate-loopback-google-facebook-github/

**Comment by wilsonh1** [comment]
Not sure why this is needed? It's not like a fake FB account would do any harm.

**Comment by ConcurrencyPractitioner** [comment]
Eh, its more like making sure that the network stays safe from attackers. Not much else. Idk this is more for overkill than anything else.
